[package]
org = "thiyan"
name = "terminology_service_api"
version = "0.1.0"
distribution = "2201.6.0"
template=true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "3.0.1"
repository = "local"

[build-options]
observabilityIncluded = true
